---
server:
  port: 8012
eureka:
  instance:
    hostname: eurekahost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/